version: '3'
services:

  app:
    build: .
    image: test/app:latest
    command: ["python", "app.py"]
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq

  worker:
    build: .
    image: test/app:latest
    command: ["celery", "worker", "--app=worker.app", "--hostname=worker@%h", "--loglevel=DEBUG"]
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: library/rabbitmq:3.6.10
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"

